const TRANSFER_TYPES = 7;
const MINUTES_IN_DAY = 1440;
const MAX_SELECTED_OFFERS_NUMBER = 3;
const MAX_AVAILABLE_OFFERS_NUMBER = 5;
const DESTINATION_PHOTOS = 5;
const MAX_DAYS_GAP = 1;

export {TRANSFER_TYPES, MINUTES_IN_DAY, MAX_SELECTED_OFFERS_NUMBER, MAX_AVAILABLE_OFFERS_NUMBER, DESTINATION_PHOTOS, MAX_DAYS_GAP};
